### ISSUE TITLE
The path is not valid. Please update your 'nav' with a valid path.

### ISSUE THREAD

**Issue by swissclash79** [OpenOLAT/OpenOLAT-docs#1]
Dear OpenOlat team

The following error appears when I try to build the site (I followed the steps you suggest in your README):

`[mkdocs-monorepo] The /var/folders/lm/q017z7cs5xj2_6fg5mv_336m0000gn/T/docs_v12nc5yc path is not valid. Please update your 'nav' with a valid path.`

It seems to be related to the mkdocs-monorepo-plugin: https://github.com/ultrabug/mkdocs-static-i18n/issues/260

Would it be possible to send me the version of the mkdocs-plugins you use for your builds?

Thank you in advance!

**Comment by gnaegi** [comment]
There is an incompatibility between the new mkdocs, monorepo and the i18n plugin we use. You have to use the following versions. 

pip3 install mkdocs==1.4.3
pip3 install mkdocs-material==9.1.20
